#configuation for robot odometry EKF
#
frequency: 2
two_d_mode: true
publish_tf: true
odom_frame: odom
base_link_frame: base_link
world_frame: odom
map_frame: map


imu0: /imu/data_raw
imu0_config: [false,false,false,
              true,true,true,
              false,false,false,
              true,true,true,
              true,false,false]

imu0_differential: false

odom0: /odometry/gps
odom0_config: [false,false,false,
               false,false,false,
               true,true,false,
               false,false,true,
               false,false,false]
odom0_differential: false

